#!/usr/bin/env python3
import subprocess
import json
import os
import sys
import shutil

class CodeFreshener:
    def __init__(self):
        self.report_path = "code-smell-report.json"

    def run_hermes(self, prompt):
        """Wrapper to talk to Hermes with real-time streaming output."""
        cmd = [
            "hermes", 
            "chat", 
            "-q", prompt,
            "--toolsets", "skills,terminal,read_file"
        ]
        
        # We use Popen instead of run to get a pipe we can read from live
        process = subprocess.Popen(
            cmd, 
            stdout=subprocess.PIPE, 
            stderr=subprocess.STDOUT, # Merge errors into the same stream
            text=True,
            bufsize=1
        )

        full_output = []
        
        # Read the output line by line as Hermes generates it
        for line in iter(process.stdout.readline, ""):
            print(line, end="") # Print to your terminal immediately
            full_output.append(line)
        
        process.stdout.close()
        return_code = process.wait()

        if return_code != 0:
            print(f"\n❌ Hermes exited with error code {return_code}")
            return None
            
        return "".join(full_output)

    def analyze(self, repo_url):
        """Step 2: Trigger the 'code-smell-spotter' Skill to audit the codebase."""
        print(f"🕵️ Auditing the codebase at {repo_url}...")
        
        # We tell Hermes to look in the local directory './target_repo'
        prompt = f"""
        /code-smell-spotter audit the repository at {repo_url} using code-smell-spotter skill.
        First use the command `npx repomix@latest` pack the repository into a single file.
        which will create repomix-output.xml and use it for the analysis.
        Dont use 'cat' on files, you only need to use the repomix-output.xml file. 
        
        Also use logs format for each step:
        1. [STEP][CLONING] Cloning the repository at {repo_url}...
        2. [STEP][PACKAGING]: Packaging the repository for analysis.
        3. [STEP][ANALYZING]: Analysing the codebase for code smells.
        4. [STEP][REPORTING]: Creating the report...
        """
        output = self.run_hermes(prompt)
        
        if output:
            print("\n--- Agent Summary ---")
            print(output)
            print("----------------------\n")
        
        self.display_report()

    def display_report(self):
        """Read and display the resulting JSON report generated by the agent."""
        if not os.path.exists(self.report_path):
            print(f"⚠️  Report file not found. Ensure your Skill writes to {self.report_path}")
            return

        with open(self.report_path, "r") as f:
            try:
                report = json.load(f)
            except json.JSONDecodeError:
                print("❌ Error: The agent generated an invalid JSON report.")
                return

        metadata = report.get("metadata", {})
        print(f"✅ Audit Complete: {metadata.get('total_smells_found', 0)} smells found.")
        
        scores = report.get("file_quality_scores", {})
        # Sort by quality so the 'worst' files show up first
        for file, data in sorted(scores.items(), key=lambda x: x[1].get('quality_percentage', 100)):
            q = data.get('quality_percentage', 100)
            status = "🔴" if q < 75 else "🟡" if q < 90 else "🟢"
            print(f"{status} {file}: {q}% Quality")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: ./freshen.py <github_url>")
        sys.exit(1)

    freshener = CodeFreshener()
    freshener.analyze(sys.argv[1])